# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Box Ubuntu 20.04 LTS
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20240821.0.1"

  # Network
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"

  # Shared folder
  config.vm.synced_folder "../", "/vagrant"

  # VirtualBox settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    # Update package list
    sudo apt-get update -y

    # Install Apache2
    sudo apt-get install -y apache2
    sudo systemctl enable apache2
    sudo systemctl start apache2

    # Install Docker & Docker Compose
    sudo apt-get install -y docker.io docker-compose
    sudo usermod -aG docker vagrant
    sudo systemctl enable docker
    sudo systemctl start docker

    # Install Make, Git, Net-tools
    sudo apt-get install -y make git net-tools
  SHELL
end
